### PR TITLE
More updates to the README (mostly Docker-related)

### PR DESCRIPTION
**Pull request by fklemme**
A couple of improvements from user feedback on discord.
Uppercase headers in the CSV example led to some confusion. Better make sure it's consistent with the actual file header.
Edit: More problems and solutions added to the README.

### CODE REVIEW

**Comment by fklemme** [comment]
Maybe we should even make a shared folder with some royalty-free cards to include as a working example. Could also be great for testing!

**Comment by fklemme** [comment]
I did set up a small shared folder and added it as an example. It contains a few cards without any artwork (generated with Proximity). Good enough for testing and as an example how to add a drive.

**Comment by chilli-axe** [comment]
nice work on the example drive! one idea i had is when local files are supported, having to set up a google scripts api & putting `credentials.json` could become optional and we could only check to see if the file is there `drives.csv` has data in it - the example drive is great for now, just some food for thought!

**Comment by fklemme** [comment]
Yeah, I had the same thought. But as long as local files are not the standard, it should be fine. And when we finished implementing local files, we can just put it as an example into the readme or something.

**Pull request merged**
