### PR TITLE
fix(MPCAutofill): missing Django env variable

### LINKED ISSUE #101: FATAL:  database "/MPCAutofill/MPCAutofill/card_db.db" does not exist
Clean setup:
- `MPCAutofill/client_secrets.json` exists and populated
- `MPCAutofill/drives.csv` exists and populated
- `MPCAutofill/MPCAutofill/.env` file exists and populated
- In `docker` directory, ran `./docker_clean_all.bat`
- In `docker` directory, ran `docker compose up --build`

Full error message:
`django.db.utils.OperationalError: connection to server at "postgres" (172.24.0.3), port 5432 failed: FATAL:  database "/MPCAutofill/MPCAutofill/card_db.db" does not exist`

Maybe the `django/Dockerfile` needs a step to generate `/MPCAutofill/MPCAutofill/card_db.db`? Does the `update_database.sh` script do this?

Full log:
```
docker-django-1         | 14 static files copied to '/MPCAutofill/static', 140 unmodified, 107 post-processed.
docker-postgres-1       | 2022-10-30 02:27:34.289 UTC [29] FATAL:  database "/MPCAutofill/MPCAutofill/card_db.db" does not exist
docker-django-1         | Traceback (most recent call last):
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 282, in ensure_connection
docker-django-1         |     self.connect()
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 26, in inner
docker-django-1         |     return func(*args, **kwargs)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 263, in connect
docker-django-1         |     self.connection = self.get_new_connection(conn_params)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 26, in inner
docker-django-1         |     return func(*args, **kwargs)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/postgresql/base.py", line 215, in get_new_connection
docker-django-1         |     connection = Database.connect(**conn_params)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/psycopg2/__init__.py", line 122, in connect
docker-django-1         |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
docker-django-1         | psycopg2.OperationalError: connection to server at "postgres" (172.24.0.3), port 5432 failed: FATAL:  database "/MPCAutofill/MPCAutofill/card_db.db" does not exist
docker-django-1         | 
docker-django-1         | 
docker-django-1         | The above exception was the direct cause of the following exception:
docker-django-1         | 
docker-django-1         | Traceback (most recent call last):
docker-django-1         |   File "/MPCAutofill/MPCAutofill/manage.py", line 21, in <module>
docker-django-1         |     main()
docker-django-1         |   File "/MPCAutofill/MPCAutofill/manage.py", line 17, in main
docker-django-1         |     execute_from_command_line(sys.argv)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
docker-django-1         |     utility.execute()
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 440, in execute
docker-django-1         |     self.fetch_command(subcommand).run_from_argv(self.argv)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 402, in run_from_argv
docker-django-1         |     self.execute(*args, **cmd_options)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 448, in execute
docker-django-1         |     output = self.handle(*args, **options)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 96, in wrapped
docker-django-1         |     res = handle_func(*args, **kwargs)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/commands/migrate.py", line 114, in handle
docker-django-1         |     executor = MigrationExecutor(connection, self.migration_progress_callback)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/executor.py", line 18, in __init__
docker-django-1         |     self.loader = MigrationLoader(self.connection)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/loader.py", line 58, in __init__
docker-django-1         |     self.build_graph()
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/loader.py", line 235, in build_graph
docker-django-1         |     self.applied_migrations = recorder.applied_migrations()
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/recorder.py", line 81, in applied_migrations
docker-django-1         |     if self.has_table():
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/recorder.py", line 57, in has_table
docker-django-1         |     with self.connection.cursor() as cursor:
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 26, in inner
docker-django-1         |     return func(*args, **kwargs)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 323, in cursor
docker-django-1         |     return self._cursor()
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 299, in _cursor
docker-django-1         |     self.ensure_connection()
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 26, in inner
docker-django-1         |     return func(*args, **kwargs)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 281, in ensure_connection
docker-django-1         |     with self.wrap_database_errors:
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/utils.py", line 91, in __exit__
docker-django-1         |     raise dj_exc_value.with_traceback(traceback) from exc_value
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 282, in ensure_connection
docker-django-1         |     self.connect()
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 26, in inner
docker-django-1         |     return func(*args, **kwargs)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 263, in connect
docker-django-1         |     self.connection = self.get_new_connection(conn_params)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 26, in inner
docker-django-1         |     return func(*args, **kwargs)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/postgresql/base.py", line 215, in get_new_connection
docker-django-1         |     connection = Database.connect(**conn_params)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/psycopg2/__init__.py", line 122, in connect
docker-django-1         |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
docker-django-1         | django.db.utils.OperationalError: connection to server at "postgres" (172.24.0.3), port 5432 failed: FATAL:  database "/MPCAutofill/MPCAutofill/card_db.db" does not exist
docker-django-1         | 
docker-django-1         | Migrate Django database...
docker-postgres-1       | 2022-10-30 02:27:35.539 UTC [30] FATAL:  database "/MPCAutofill/MPCAutofill/card_db.db" does not exist
docker-django-1         | Traceback (most recent call last):
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 282, in ensure_connection
docker-django-1         |     self.connect()
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 26, in inner
docker-django-1         |     return func(*args, **kwargs)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 263, in connect
docker-django-1         |     self.connection = self.get_new_connection(conn_params)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 26, in inner
docker-django-1         |     return func(*args, **kwargs)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/postgresql/base.py", line 215, in get_new_connection
docker-django-1         |     connection = Database.connect(**conn_params)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/psycopg2/__init__.py", line 122, in connect
docker-django-1         |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
docker-django-1         | psycopg2.OperationalError: connection to server at "postgres" (172.24.0.3), port 5432 failed: FATAL:  database "/MPCAutofill/MPCAutofill/card_db.db" does not exist
docker-django-1         | 
docker-django-1         | 
docker-django-1         | The above exception was the direct cause of the following exception:
docker-django-1         | 
docker-django-1         | Traceback (most recent call last):
docker-django-1         |   File "/MPCAutofill/MPCAutofill/manage.py", line 21, in <module>
docker-django-1         |     main()
docker-django-1         |   File "/MPCAutofill/MPCAutofill/manage.py", line 17, in main
docker-django-1         |     execute_from_command_line(sys.argv)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
docker-django-1         |     utility.execute()
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 440, in execute
docker-django-1         |     self.fetch_command(subcommand).run_from_argv(self.argv)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 402, in run_from_argv
docker-django-1         |     self.execute(*args, **cmd_options)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 448, in execute
docker-django-1         |     output = self.handle(*args, **options)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 96, in wrapped
docker-django-1         |     res = handle_func(*args, **kwargs)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/commands/migrate.py", line 114, in handle
docker-django-1         |     executor = MigrationExecutor(connection, self.migration_progress_callback)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/executor.py", line 18, in __init__
docker-django-1         |     self.loader = MigrationLoader(self.connection)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/loader.py", line 58, in __init__
docker-django-1         |     self.build_graph()
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/loader.py", line 235, in build_graph
docker-django-1         |     self.applied_migrations = recorder.applied_migrations()
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/recorder.py", line 81, in applied_migrations
docker-django-1         |     if self.has_table():
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/recorder.py", line 57, in has_table
docker-django-1         |     with self.connection.cursor() as cursor:
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 26, in inner
docker-django-1         |     return func(*args, **kwargs)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 323, in cursor
docker-django-1         |     return self._cursor()
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 299, in _cursor
docker-django-1         |     self.ensure_connection()
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 26, in inner
docker-django-1         |     return func(*args, **kwargs)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 281, in ensure_connection
docker-django-1         |     with self.wrap_database_errors:
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/utils.py", line 91, in __exit__
docker-django-1         |     raise dj_exc_value.with_traceback(traceback) from exc_value
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 282, in ensure_connection
docker-django-1         |     self.connect()
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 26, in inner
docker-django-1         |     return func(*args, **kwargs)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 263, in connect
docker-django-1         |     self.connection = self.get_new_connection(conn_params)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 26, in inner
docker-django-1         |     return func(*args, **kwargs)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/postgresql/base.py", line 215, in get_new_connection
docker-django-1         |     connection = Database.connect(**conn_params)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/psycopg2/__init__.py", line 122, in connect
docker-django-1         |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
docker-django-1         | django.db.utils.OperationalError: connection to server at "postgres" (172.24.0.3), port 5432 failed: FATAL:  database "/MPCAutofill/MPCAutofill/card_db.db" does not exist
docker-django-1         | 
docker-django-1 exited with code 1
```

### PR DESCRIPTION
**Pull request by mcapu**
Fixes #101

### CODE REVIEW

**Comment by mcapu** [comment]
I'd appreciate some help with the tests -- I'm not sure how adding this line could break them, especially the formatting/type checking.

**Comment by ndepaola** [comment]
sorry for forgetting to get to this now. thanks for the PR :) will merge now

with regards to the tests failing - this is the relevant bit from the readme:

> GitHub Actions is configured in this repository to run the Django project's end-to-end tests. To run these, it needs to access the Google Drive API, and does so through a repository secret named GOOGLE_DRIVE_API_KEY. If you fork this project, you'll need to set this repository secret for GitHub Actions to run these tests for you.

unfortunately when you put up a PR targeting my repo from your fork of it, github actions runs the tests on your repo, meaning they're always going to fail unless you set the repo secret for the gdrive api secret key. i should make that clearer in the readme :)

**Comment by davidianstyle** [comment]
@ndepaola is the `GOOGLE_DRIVE_API_KEY` supposed to be a service account JSON file with access to Google Drive API? I've noticed the same tests failing so I'm trying to get them to go green by supplying the secret in my forked repo.

**Comment by davidianstyle** [comment]
Screenshot 2023-03-14 at 1 34 39 PM
Answered my own question. That seemed to have worked!

**Pull request merged**
